language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.3.7
  - DJANGO=django==1.4.10
  - DJANGO=django==1.5.5
  - DJANGO=django==1.6.2

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install https://github.com/jorgebastida/django-app-test-runner/zipball/master

script:
  - app-test-runner dajaxice dajaxice

branches:
  only:
    - master
    - develop

matrix:
  exclude:
    # Django>1.5 strongly recommends python 2.7 or later (so skip 2.6)
    - python: "2.6"
      env: DJANGO=django==1.5.5
    - python: "2.6"
      env: DJANGO=django==1.5.5

