# Generated by Django 2.0.5 on 2025-08-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('django_reusable', '0002_auto_20230920_1601'),
    ]

    dependencies = [
        ('django_reusable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'ordering': ['-last_seen']},
        ),
    ]
