# Generated by Django 2.0.5 on 2025-08-28 05:47

from django.db import migrations, models
import django_reusable.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20221206_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='home_address',
            field=django_reusable.models.fields.USAddressField(blank=True, help_text='Home address', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='work_address',
            field=django_reusable.models.fields.USAddressField(blank=True, help_text='Work address', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('Software Engineer', 'IT - Software Engineer'), ('Manager', 'General - Manager')], max_length=30, null=True),
        ),
    ]
