# Generated by Django 2.0.5 on 2025-08-28 06:31

from django.db import migrations
import django_reusable.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20250828_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='address',
            field=django_reusable.models.fields.USAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_address',
            field=django_reusable.models.fields.USAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_address',
            field=django_reusable.models.fields.USAddressField(blank=True, null=True),
        ),
    ]
