# Generated by Django 2.0.5 on 2025-09-01 19:31

from django.db import migrations
import django_reusable.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20250828_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='roles',
            field=django_reusable.models.fields.MultipleChoiceField(blank=True, null=True),
        ),
    ]
