# Generated by Django 2.0.5 on 2025-09-26 21:55

from django.db import migrations
import django_reusable.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_person_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='gdp',
            field=django_reusable.models.fields.CurrencyField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='net_worth',
            field=django_reusable.models.fields.CurrencyField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=django_reusable.models.fields.MultipleChoiceField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User'), ('Guest', 'Guest')], null=True),
        ),
    ]
